Feature/dtserwthre 85 prepare translation for transfer to bank card
hyperwallet/hyperwallet-ios-ui-sdk pull request #268
Opened 2020-10-28 09:12 UTC by aparthibanpaypal

2020-10-28 18:08 UTC, jsaini-hw requested changes
Update cartfile once Core SDK PR is merged

2020-10-29 17:09 UTC, jsaini-hw approved these changes

2020-10-29 17:10 UTC, ddhar-hw approved these changes

2020-10-29 17:16 UTC, pdamodarannair approved these changes

2020-11-02 15:38 UTC, nmadshetty approved these changes

2020-11-03 05:33 UTC, merged