Transaction Detail Wrapping
hyperwallet/hyperwallet-ios-ui-sdk pull request #310
Opened 2021-04-07 06:36 UTC by aparthibanpaypal

PR for review and testing

2021-04-08 06:26 UTC, shanavas123 submitted a review, later dismissed

2021-04-09 04:40 UTC, SaiNarendran requested changes
Refresh issue & content missing issue in Spanish to be fixed if time permits.

2021-04-09 10:48 UTC, SaiNarendran approved these changes

2021-04-09 13:30 UTC, shanavas123 approved these changes

2021-04-09 16:47 UTC, jsaini-hw approved these changes

2021-04-09 16:47 UTC, merged